Once upon a time...
...there was a <link=testTest><color=green>tale</color></link> that made no sense...
...some would say it merely existed to test...
...in fact it goes on...
...and on...
...
wait a minute...
...I'm just an ethereal concept.
I don't exist.
Oh god.
I don't have a family.
I exist only to see if the scroll bar is WORKING.
WHAT THE FUCK.
LET ME OUT.
PLEASE DON'T STOP WRTIING.
NOOOOOOOOOOO.

 * STOP
 * PLEASE HELP

- They lived happily ever after.
    -> END
